name: API Endpoint Tests

on:
  - push

jobs:
  test:
    environment: declension-bot
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp bs4 pytest python-dotenv
    - name: Run tests
      working-directory: ./tests
      env:
        PYTHONWARNINGS: ignore::DeprecationWarning
        DECLINATOR_API_TOKEN: ${{ secrets.DECLINATOR_API_TOKEN }}
        RAPID_API_TOKEN: ${{ secrets.RAPID_API_TOKEN }}
      run: |
        pytest
