name: API Endpoint Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp bs4 pytest
    
    - name: Run tests
      env:
        PYTHONWARNINGS: ignore::DeprecationWarning
        DECLINATOR_API_TOKEN: ${{ secrets.DECLINATOR_API_TOKEN }}
        RAPID_API_TOKEN: ${{ secrets.RAPID_API_TOKEN }}
      run: |
        pytest tests/test_endpoints.py --no-header --tb=short
